Add dependencies to run sysvinit tasks on systemd systems
beaker-project/beaker-core-tasks pull request #1
Opened 2019-10-24 12:42 UTC by renanrodrigo

2019-10-24 12:44 UTC, StykMartin commented
Missing Bug ID :eyes:

2019-10-24 13:44 UTC, StykMartin commented on virt/image-install/Makefile
> +	@echo "Requires:	iptables-servce" >> $(METADATA)
Do we even need this service? + typo

2019-10-24 13:44 UTC, StykMartin commented on virt/install/Makefile
> +	@echo "Requires:	iptables-servce" >> $(METADATA)
Do we even need this service? + typo

2019-10-24 13:45 UTC, cbouchar requested changes
should be iptables-service NOT iptables-servce in both locations

2019-10-31 14:46 UTC, StykMartin approved these changes
Looks good.
Did you try both **image-install** and **install** ?

2019-10-31 15:33 UTC, renanrodrigo commented
I tried virt/install so far.
The iptables-service line wasn't necessary after all.
I'm running virt/image-install to check results.

2019-11-01 15:14 UTC, cbouchar approved these changes

2019-11-02 12:06 UTC, merged